spring:
  application:
    name: mental-health-user-auth
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    datasource:
      url: jdbc:postgresql://${db_host:localhost}:5432/${db_name:mh-user-auth-db}
      username: ${db_user}
      password: ${db_password}
      driverClassName: org.postgresql.Driver

server:
  port: 8082
  servlet:
    context-path: ${spring.application.name}